name: aikido_helper
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  csv: ^5.0.2
  flutter_markdown: ^0.6.17
  url_launcher: ^6.2.5
  path_provider: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/logo.jpg
      - assets/images/icon_github.png
      - assets/technique/technique.csv
      - assets/technique/technique_ordering.csv
      - assets/markdowns/
