name: Prevent Non-dev PRs to Main

on:
  pull_request:
    branches:
      - main

jobs:
  block-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          echo "Source: ${{ github.head_ref }}"
          if [[ "${{ github.head_ref }}" != "dev" ]]; then
            echo "❌ Only PRs from 'dev' are allowed to merge into 'main'."
            exit 1
          else
            echo "✅ Valid PR from 'dev' branch."
          fi
